#!/bin/bash

. /etc/sshtunnel.conf

/usr/bin/ssh -N \
   -o "ServerAliveInterval 60" \
   -o "ServerAliveCountMax 3" \
   -o ExitOnForwardFailure=yes \
   -o StrictHostKeyChecking=no \
   -o TCPKeepAlive=yes \
   -p 22 -l ${REMOTE_USER} -R ${REMOTE_PORT}:127.0.0.1:22 -i /home/root/.ssh/id_rsa ${REMOTE_HOST}
